#!/bin/bash
# Monocyte - An AWS Resource Destroyer
# Copyright 2015 Immobilien Scout GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e -E -u -C -o pipefail

VENV=${1:-venv}

die() {
    echo $@
    exit 1
}

which virtualenv > /dev/null || die "cannot find program 'virtualenv'; please install first"
[[ -d src ]] || die "no src dir found, aborting!"

rm -rf $VENV
virtualenv $VENV

set +u
. $VENV/bin/activate
set -u
pip install pybuilder
pyb install_dependencies

ln -s $PWD/src/main/scripts/* $VENV/bin/
ln -s $PWD/src/main/python/* $VENV/lib/python*/site-packages/

echo
echo "remember to 'source $VENV/bin/activate' in order to use this virtualenv"
echo
