#!/bin/bash
set -e -E -u -C -o pipefail

VENV=${1:-venv}

die() {
    echo $@
    exit 1
}

which virtualenv > /dev/null || die "cannot find program 'virtualenv'; please install first"
[[ -d src ]] || die "no src dir found, aborting!"

rm -rf $VENV
virtualenv $VENV

set +u
. $VENV/bin/activate
set -u
pip install pybuilder
pyb install_dependencies

ln -s $PWD/src/main/scripts/* $VENV/bin/
ln -s $PWD/src/main/python/* $VENV/lib/python*/site-packages/

echo
echo "remember to 'source $VENV/bin/activate' in order to use this virtualenv"
echo
