#!/usr/bin/env python
"""
Usage:
    monocyte [--dry-run=bool]

options:
    --dry-run=bool valid values "True" or "False" [default: True]
"""

import sys

from docopt import docopt
from monocyte import Monocyte

arguments = docopt(__doc__)

dry_run = (arguments["--dry-run"] != "False")
sys.exit(Monocyte().search_and_destroy_unwanted_resources(dry_run))
