#!/bin/bash

set -e -E -u

die(){
    echo $@
    exit 1
}

LOG_DIR=/var/log/monocyte

[[ -d $LOG_DIR ]] || die "cannot find log dir $LOG_DIR"

LOGFILE=${LOG_DIR}/monocyte.$(date +%Y-%m-%dT%H:%M:%S).log

if monocyte --dry-run=True >$LOGFILE 2>&1; then
    :
else
    echo "ERROR is occured"
    cat $LOGFILE
fi
