#!/usr/bin/env python
"""
Usage:
    monocyte
"""

import sys

from docopt import docopt
from monocyte import Monocyte

arguments = docopt(__doc__)

sys.exit(Monocyte().search_and_destroy_unwanted_resources())
