#!/usr/bin/env python
# Monocyte - Search and Destroy unwanted AWS Resources relentlessly.
# Copyright 2015 Immobilien Scout GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
usage:
    monocyte [options]

options:
    --dry-run=bool valid values "True" or "False"
    --config-path=PATH path to config yaml files
    --whitelist=S3-URI uri to whitelist yaml file
"""

import sys
from docopt import docopt

import monocyte.cli as cli


def run():
    arguments = docopt(__doc__)
    sys.exit(cli.main(arguments))


if __name__ == "__main__":
    run()
